// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ROt0ruPRaJj2qHU0mDaed0urqwjlY0U',
    appId: '1:407982710204:web:0b3148dfe1a3a2170a1fb9',
    messagingSenderId: '407982710204',
    projectId: 'ekkankoon-food',
    authDomain: 'ekkankoon-food.firebaseapp.com',
    storageBucket: 'ekkankoon-food.firebasestorage.app',
    measurementId: 'G-RJCR082MDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO4L5ZGyFVZUI4Ng9m8fEEvnxbb-C3bqo',
    appId: '1:407982710204:android:3aa1549ebb6545170a1fb9',
    messagingSenderId: '407982710204',
    projectId: 'ekkankoon-food',
    storageBucket: 'ekkankoon-food.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPMT_b3VNowGL29KULCFawPzqhFqo8vL8',
    appId: '1:407982710204:ios:0c860edd7c48518e0a1fb9',
    messagingSenderId: '407982710204',
    projectId: 'ekkankoon-food',
    storageBucket: 'ekkankoon-food.firebasestorage.app',
    iosBundleId: 'com.example.nattanon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPMT_b3VNowGL29KULCFawPzqhFqo8vL8',
    appId: '1:407982710204:ios:0c860edd7c48518e0a1fb9',
    messagingSenderId: '407982710204',
    projectId: 'ekkankoon-food',
    storageBucket: 'ekkankoon-food.firebasestorage.app',
    iosBundleId: 'com.example.nattanon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7ROt0ruPRaJj2qHU0mDaed0urqwjlY0U',
    appId: '1:407982710204:web:c530affddde1be100a1fb9',
    messagingSenderId: '407982710204',
    projectId: 'ekkankoon-food',
    authDomain: 'ekkankoon-food.firebaseapp.com',
    storageBucket: 'ekkankoon-food.firebasestorage.app',
    measurementId: 'G-PJV8JPCKQ4',
  );
}
